apiVersion: v1
kind: Namespace
metadata:
  name: perfdash
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfdash
  namespace: perfdash
  labels:
    app.kubernetes.io/name: perfdash
    app.kubernetes.io/version: "2.44"
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/part-of: perfdash
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: perfdash
      app.kubernetes.io/version: "2.44"
      app.kubernetes.io/component: dashboard
      app.kubernetes.io/part-of: perfdash
  template:
    metadata:
      labels:
        app.kubernetes.io/name: perfdash
        app.kubernetes.io/version: "2.44"
        app.kubernetes.io/component: dashboard
        app.kubernetes.io/part-of: perfdash
    spec:
      containers:
        - name: perfdash
          image: gcr.io/k8s-staging-perf-tests/perfdash:2.44
          command:
            - /perfdash
            - --www=true
            - --address=0.0.0.0:8080
            - --builds=100
            - --force-builds
            - --mode=s3
            - --aws-region=us-west-2
            - --configPath=/etc/config/jobs.yaml
            - --logsBucket=kit-eks-scalability
            - --logsPath=
            - --allow-parsers-matching-all-tests=true
          imagePullPolicy: Always
          ports:
            - name: status
              containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 1
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: perfdash-config
---
apiVersion: v1
kind: Service
metadata:
  name: perfdash-status
  namespace: perfdash
  labels:
    app.kubernetes.io/name: perfdash
    app.kubernetes.io/part-of: perfdash
spec:
  selector:
    app.kubernetes.io/name: perfdash
    app.kubernetes.io/part-of: perfdash
  ports:
    - name: status
      port: 8080
      targetPort: status
  type: NodePort
