name: Dependent

on:
  pull_request:
    branches: [main]
  push:
    branches-ignore: [main]
  workflow_run:
    workflows: [Dependent]
    types: [completed]  
permissions:
  id-token: write
  pull-requests: write
  contents: write
jobs:
  release:
    if: github.repository == 'Ganiredi/kubernetes-iteration-toolkit'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/authenticate-aws
        