name: Workflow-run-dependent
on:
  push:
    branches: ['main' ,'Github-Workflow-Kitctl']
permissions:
  id-token: write
  pull-requests: write
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Used for parent workflow file
        uses: actions/checkout@v3
      - uses: ./.github/actions/authenticate-aws