name: Release
on:
  push:
    tags: ['v*.*.*']
    branches: [ main ]
permissions:
  id-token: write
  pull-requests: write
  contents: write
jobs:
  release:
   #if: github.event.workflow_run.conclusion == 'success' && github.repository == 'Ganiredi/kubernetes-iteration-toolkit' && contains(fromJson('["push"]'), github.event.workflow_run.event)
    runs-on: ubuntu-latest
    steps:
      - name: will run childworkflow
        uses: actions/checkout@v3
      - uses: ./.github/actions/install-go-and-dependencies
      - uses: ./.github/actions/authenticate-aws