name: Release
on:
  push:
    tags: ['v*']
  workflow_dispatch: {}
permissions:
  id-token: write
  pull-requests: write
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: will run childworkflow
        uses: actions/checkout@v3
      - uses: ./.github/actions/install-go-and-dependencies
      - uses: ./.github/actions/authenticate-aws