name: This workflow automates the build, testing, and bootstrapping of a test environment on Kubernetes
on:
  pull_request:
    branches: [main]
  push:
    branches-ignore: [main]
  workflow_dispatch: {}
permissions:
  id-token: write
  contents: read
jobs:
  build-cli-macos:
    strategy:
      matrix:
        os: ["darwin"]
        arch: ["amd64"]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin/
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.1"
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::078365735624:role/github-Token-generate
          role-session-name: githubworkflowsession
          aws-region: us-west-2
      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -L -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/darwin/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
      - name: Builds the KIT CLI ,Provisions the Kit Environment and deletes it
        run: |
          cd /Users/runner/work/kubernetes-iteration-toolkit/kubernetes-iteration-toolkit/substrate/cmd/kitctl
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -v .
          ./kitctl bootstrap kit-github-${{ github.run_id }}
          sleep 30
          export KUBECONFIG=/Users/runner/.kit/env/kit-github-${{ github.run_id }}/etc/kubernetes/admin.conf
          sleep 10
          kubectl get pods -A
          for i in {1..5}; do
           if ./kitctl delete kit-github-${{ github.run_id }}; then
           break
          fi
          if [ $i -eq 1 ]; then
              sleep 120
          else
              sleep 30
          fi
          done
          if [ $i -eq 5 ]; then
              echo "Failed to delete the kit-github-${{ github.run_id }} environment after 5 attempts. Please manually delete the environment."
              exit 1
          fi
        working-directory: substrate
  build-cli-linux:
    strategy:
      matrix:
        os: ["linux"]
        arch: ["amd64"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin/
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.1"
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::078365735624:role/github-Token-generate
          role-session-name: githubworkflowsession
          aws-region: us-west-2
      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -L -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/  
      - name: Builds the KIT CLI ,Provisions the Kit Environment and deletes it
        run: |
          cd /home/runner/work/kubernetes-iteration-toolkit/kubernetes-iteration-toolkit/substrate/cmd/kitctl
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -v .
          ./kitctl bootstrap kit-github-${{ github.run_id }}
          sleep 30
          export KUBECONFIG=/home/runner/.kit/env/kit-github-${{ github.run_id }}/etc/kubernetes/admin.conf
          sleep 10
          kubectl get pods -A
          for i in {1..5}; do
          if ./kitctl delete kit-github-${{ github.run_id }}; then
           break
          fi
          if [ $i -eq 1 ]; then
              sleep 120
          else
              sleep 30
          fi
          done
          if [ $i -eq 5 ]; then
              echo "Failed to delete the kit-github-${{ github.run_id }} environment after 5 attempts. Please manually delete the environment."
              exit 1
          fi
        working-directory: substrate
