name: ReleaseTrigger
on:
  push:
    branches: [ main, testgha ]

jobs:
  release-trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
