name: Trigger-kit
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  depend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Message
        run: 
           echo "Triggers  second workflow kit-bootstrap"
       